name: Merge upstream branches
on:
  schedule:
    - cron: 0 0/6 * * ?
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge upstream
        run: |
          git config --global user.name 'upstream'
          git config --global user.email 'tianlong.jiang@outlook.com'
          git config --global credential.helper store
          git clone https://tianlong.jiang:${{ secrets.GITHUB_TOKEN }}@github.com/tianlongJ/scoop-proxy-cn.git tmp
          cd tmp
          git remote add upstream https://tianlong.jiang:${{ secrets.GITHUB_TOKEN }}@github.com/lzwme/scoop-proxy-cn.git
          git fetch upstream
          git merge upstream/main
          cp -f bucket/Coodesker-Portable.json bucket/coodesker.json
          git diff --cached --quiet && echo "没有需要提交的文件，跳过提交。" || git commit -am "coodesker"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
