name: Scoop Buckets Sync
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0/6 * * ?
jobs:
  sync:
    runs-on: ubuntu-latest
    # runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Sync buckets
        run: |
          cp -f .github/package.json .
          npm i --no-package-lock --no-audit --no-fund
          node .github/sync.mjs
          cp -f bucket/Coodesker-Portable.json bucket/coodesker.json
          cp -f bucket/OracleJDK8.json bucket/oracle8-jdk.json
          git diff --cached --quiet && echo "没有需要提交的文件，跳过提交。" || git commit -am "coodesker"
          git push origin main
        env:
          SYNC: 1
